### ISSUE TITLE
Can't crawl hentai from nhentai.net

### ISSUE THREAD

**Issue by JC-ProPlus** [MoeOverflow/hentaibook#15]
It's stuck at "Started". Here's what I've found in the console:
```
WebSocket connection to 'wss://h.comicbook.party/socket.io/?EIO=3&transport=websocket&sid=9c41cd01221e46bf8c2e8d82e7541bfd' failed: Error during WebSocket handshake: Unexpected response code: 200
```
No idea if it's a server-side error or there's a bug in the code? Plz fix this, I love your work so much, and I can't find an open-source alternative to this app. Many thanks.

**Comment by shincurry** [comment]
fix commits deployed. try it again, should work now.

**Comment by JC-ProPlus** [comment]
It's working now. Thanks!
