### ISSUE TITLE
制作的epub没有参考一般日本漫画书籍的形式去做啊

### ISSUE THREAD

**Issue by wing-kai** [MoeOverflow/hentaibook#6]
日本关于电子版漫画epub的制作是有规范的
甚至成立了一个协会专门制定行业通用，http://www.digital-comic.jp/

而comicbook生成的epub，图片随便一个img标签就放出来，
也没有规定翻页方向和排版，太随便了。

虽说是开源软件，但还是用点心吧。

我自己也做了一个叫epub-manga-creator的项目，或许能参考参考。

**Comment by shincurry** [comment]
mark http://www.digital-comic.jp/press_release_DCA_EPUB3.pdf

**Comment by shincurry** [comment]
中文翻译 https://github.com/moeoverflow/press_release_DCA_EPUB3_zh

**Comment by shincurry** [comment]
正在做了（咕咕咕

**Comment by wing-kai** [comment]
咕咕咕

**Comment by shincurry** [comment]
https://github.com/moeoverflow/comicepub

https://github.com/moeoverflow/comicbook/pull/8
